FROM registry.access.redhat.com/ubi8/openjdk-11

ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en'

# Configure the JAVA_OPTIONS, you can add -XshowSettings:vm to also display the heap size.
ENV JAVA_OPTIONS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"

COPY --chown=1001 target/lib/ /deployments/lib/
COPY --chown=1001 target/*-runner.jar /deployments/app.jar
